# Generated by Django 4.0.4 on 2022-06-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_name', models.CharField(max_length=100)),
                ('Patient_email', models.EmailField(max_length=100)),
                ('Patient_password', models.CharField(max_length=50)),
            ],
        ),
    ]
