# Generated by Django 4.0.4 on 2022-06-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescrip_Photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_prescrip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PatientManager.prescription'),
        ),
    ]
