# Generated by Django 4.0.4 on 2022-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManager', '0002_prescription_patient_patient_prescrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_prescrip',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_prescrip',
            field=models.ManyToManyField(blank=True, null=True, to='PatientManager.prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Prescrip_Photo',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
