# Generated by Django 4.0.4 on 2022-06-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManager', '0003_remove_patient_patient_prescrip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_prescrip',
        ),
        migrations.AddField(
            model_name='patient',
            name='Prescrip_Photo',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
